const BLOCKFROST_PROJECT_ID = process.env.BLOCKFROST_PROJECT_ID || "preprod1Bv1mpOMPCqmhMj6bgGKrem8J5CT5Yu8"
const PINATA_API_KEY = process.env.PUBLIC_NEXT_PINATA_API_KEY as string
const PINATA_API_SECRET = process.env.PUBLIC_NEXT_PINATA_API_SECRET as string
const PINATA_JWT = process.env.PUBLIC_NEXT_PINATA_JWT
const NEXT_PUBLIC_GATEWAY_URL = process.env.NEXT_PUBLIC_GATEWAY_URL as string


export const ENV = {
    BLOCKFROST_PROJECT_ID,
    PINATA_API_KEY,
    PINATA_API_SECRET,
    PINATA_JWT,
    NEXT_PUBLIC_GATEWAY_URL
}